# Generated by Django 5.1.2 on 2024-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐'), (6, '6 ⭐'), (7, '7 ⭐'), (8, '8 ⭐'), (9, '9 ⭐'), (10, '10 ⭐')])),
                ('published_date', models.DateField()),
                ('plot', models.TextField()),
            ],
        ),
    ]
